### ISSUE TITLE
Replace on bitcoin encoding crate with 0.29 release

### ISSUE THREAD

**Issue by rajarshimaitra** [LNP-BP/client_side_validation#1]
https://github.com/LNP-BP/client_side_validation/blob/dc9b15e6b507496d7e8a47eacee37291d821b0a7/strict_encoding/Cargo.toml#L23

**Comment by josediegorobles** [comment]
This issue has to be closed isn't it?

**Comment by dr-orlovsky** [comment]
Nope, because the released 0.27 version hasn't moved yet to have a separate encoding crate :) So the issue is blocked by the upstream.
