### ISSUE TITLE
When does `strict_encoding` reaches stable release?

### ISSUE THREAD

**Issue by joemphilips** [LNP-BP/client_side_validation#120]
I've been building some functionality to master branch of `lnp-node`, and I encountered some nasty build error in dependency `strict_encoding` 0.9.0.
Something like this

```sh
error[E0432]: unresolved import `bitcoin::XpubIdentifier`
  --> /home/joemphilips/.cargo/registry/src/github.com-1ecc6299db9ec823/strict_encoding-0.9.0/src/bitcoin.rs:32:21
   |
32 |     XOnlyPublicKey, XpubIdentifier,
   |                     ^^^^^^^^^^^^^^
   |                     |
   |                     no `XpubIdentifier` in the root
   |                     help: a similar name exists in the module: `PubIdentifier`
```

Not sure where this PubIdentifier came from, I could not find the name with `git log -p` in rust-bitcoin.

Anyway, I tried to debug by forking `strict_encoding`. which existed in this repository.
But I suppose it has been moved to https://github.com/strict-types/strict-encoding now?
If so, forking this repository seems not a good idea.
Probably I should wait until the `strict-encoding` in the new repository gets stable and other lnp-bp-rgb libraries depends on it? How long should I wait for it?

**Comment by dr-orlovsky** [comment]
Hi! With the release of v0.10 all LNP/BP libraries move to new strict_encoding v2.0, which is stable and final version. Update to RGB libraries is happening right now (with RGB Core v0.10 released early this month). Update of LNP libs is planned for the March.

Nevertheless the error you are reporting is really wierd and probably unrelated to `strict_encoding`, since everywhere else v0.9 was compiling. It could be some `cargo` bug, so just try to run `cargo clean` and re-compile again.

**Comment by joemphilips** [comment]
> Hi! With the release of v0.10 all LNP/BP libraries move to new strict_encoding v2.0, which is stable and final version. Update to RGB libraries is happening right now (with RGB Core v0.10 released early this month). Update of LNP libs is planned for the March.

I see, then probably I should just reference the new version in my fork and move on.
(It takes some my effort to fork all dependencies using `strict_encoding` though) 

> Nevertheless the error you are reporting is really wierd and probably unrelated to strict_encoding, since everywhere else v0.9 was compiling. It could be some cargo bug, so just try to run cargo clean and re-compile again.

I had tried it. I also tried removing all strict encoding src under `~/.cargo/registry` but having same error.
It is really weird, indeed.

**Comment by joemphilips** [comment]
I deleted a whole cache by `rm -rf ~/.cargo/registry` and now it seems working.
Perhaps I mistakenly edited `bitcoin` crate source code under the registry folder by my hand. Sorry for bothering you,
