### ISSUE TITLE
broken MerkleBlock conceal procedure

### ISSUE THREAD

**Issue by zoedberg** [LNP-BP/client_side_validation#124]
Executing rgb-lib tests we found an issue that sometimes happens and seems very similar to https://github.com/RGB-WG/rgb-node/issues/208, but I'm not sure it's the same.

The error we receive is `MerkleBlock conceal procedure is broken` and comes from `~/.cargo/git/checkouts/client_side_validation-8dff74d720902144/46cb8a7/commit_verify/src/mpc/block.rs:418:21`.

@dr-orlovsky could you please investigate this?

**Comment by dr-orlovsky** [comment]
No, this appears to be an issue unrelated to the original one. Investigating its possible source. Can you pls provide me with the source data with which you are getting this panic?

**Comment by nicbus** [comment]
Here's the `stock.dat` file for a wallet that encounters the issue while calling `.transfer(contract_id, beneficiaries)` on the `Runtime` (in a regtest environment).

[stock.dat.zip](https://github.com/LNP-BP/client_side_validation/files/11600945/stock.dat.zip)

**Comment by dr-orlovsky** [comment]
@nicbus should be solved with https://github.com/LNP-BP/client_side_validation/pull/125

Can you  pls check & confirm that the solution works for your tests?
