### ISSUE TITLE
MerkleBlock conceal_except clarification

### ISSUE THREAD

**Issue by zoedberg** [LNP-BP/client_side_validation#162]
While trying to better understand the inner details of the `MerkleBlock` conceal procedure, I've inspected the [`conceal_except` method](https://github.com/LNP-BP/client_side_validation/blob/master/commit_verify/src/mpc/block.rs#L273), noticing that it gets an array of `ProtocolId`s. But looking at all calls made to this method I've also noticed that the method gets called either with an empty array or with an array containing a single `ProtocolId`. Therefore I've tried to change the method signature to get instead an `Option<ProtocolId>`, adjusted the caller methods and confirmed this still produces a valid commitment ID for the merkle block.

So I'm wondering if the array in the method signature is a leftover and, if so, if we can change the method signature and implementation, for the sake of simplifying the code and its auditing.

**Comment by dr-orlovsky** [comment]
Well, I am always trying to design modules and libraries such that they do not assume anything about their callers. Thus, MPC doesn't know how RGB protocol works or that `ProtocolId` is a `ContractId`. So I just have made a generic function which can work with any protocol on top, including protocols needing concealing multiple ids at the same time.

But I agree that better API is possible. Probably adding methods `conceal_all` taking zero args, renaming `conceal_except` into `conceal_except_all`, and do a new `conceal_except` method taking a single protocol id is the right way to do.

**Comment by dr-orlovsky** [comment]
So is the question resolved?

**Comment by dr-orlovsky** [comment]
Ok, there already was a `MerkleBlock::conceal` method from `Conceal` trait implementation which conceals everything. I have added `::conceal_other` for a single-protocol case, but since it is called from just one place I think this is nothingburger. Anyway, here is a PR: https://github.com/LNP-BP/client_side_validation/pull/164
