### ISSUE TITLE
Re-implement strict encoding for arrays with const generics once MSRV > 1.50

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/client_side_validation#19]

**Comment by josediegorobles** [comment]
Hi, i don't see the array implementation of strict encoding

**Comment by dr-orlovsky** [comment]
Here they are: https://github.com/LNP-BP/client_side_validation/blob/master/strict_encoding/src/pointers.rs#L36-L94

Basically what we need is to have just a single one in form of `impl<Len> StrictEncode/Decode for [u8; Len]`

**Comment by dr-orlovsky** [comment]
Closed in #45
