### ISSUE TITLE
StrictEncoding issue with enum tuple struct field initialization

### ISSUE THREAD

**Issue by cryptoquick** [LNP-BP/client_side_validation#54]
When fixing some clippy lints on the descriptor wallet, I ran into an issue here:

![Screenshot from 2022-02-09 12-30-55](https://user-images.githubusercontent.com/285690/153277402-0ccd25d7-ec99-43f5-baa7-7522ec966fb0.png)

Docs on the linter rule are here:
https://rust-lang.github.io/rust-clippy/master/index.html#init_numbered_fields

Normally I wouldn't file a feature request just to satisfy a linter, but this might be indicative of some sort of oversight. Feel free to close if we're comfortable with using `#![allow(clippy::init_numbered_fields)]` in all projects using strict encoding.

**Comment by dr-orlovsky** [comment]
Hm, not sure I understand what specifically linter does not like here and how it can be fixed. Any ideas?

**Comment by dr-orlovsky** [comment]
sorry for closing, pressed the wrong button

**Comment by cryptoquick** [comment]
It looks like this is a problem that might be fixed once 1.59 is released:
https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#new-lints

I noticed it goes away if the nightly toolchain is used.

**Comment by dr-orlovsky** [comment]
1.59 got released. Can we close this issue?

**Comment by cryptoquick** [comment]
No, it's just that the lint is in stable now. The issue persists.

**Comment by cryptoquick** [comment]
🎉

**Comment by dr-orlovsky** [comment]
Thank you for bringing the attention to the issue!
