### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by cryptoquick** [LNP-BP/client_side_validation#93]
stens fails to compile to wasm32-unknown-unknown due to the dependency, amplify_syn.

**Comment by dr-orlovsky** [comment]
I actually would like to get all stack working on WASM, but have no experience with it. The amplify library was created by me, so I am able to fix it. Can you file an issue in github.com/rust-amplify/rust-amplify please? Do you have any ideas how the compile failure can be fixed?

**Comment by cryptoquick** [comment]
Issue moved to https://github.com/rust-amplify/rust-amplify/issues/143
